# Generated by Django 3.0.8 on 2020-10-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200725_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={},
        ),
    ]
